# Generated by Django 4.0.7 on 2022-11-22 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'id_box')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='import_no',
        ),
        migrations.RemoveField(
            model_name='medicinerecipe',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='tankplanning',
            name='care_schedule',
        ),
        migrations.RemoveField(
            model_name='tankplanning',
            name='water_level',
        ),
        migrations.RemoveField(
            model_name='tankplanning',
            name='water_level_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='workmonitoring',
            name='care',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='medicinerecipetype',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hatchery.disease'),
        ),
        migrations.AddField(
            model_name='season',
            name='building',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='hatchery.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tankplanning',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'InProcess'), (2, 'Ended')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hatchery.building'),
        ),
        migrations.AddField(
            model_name='workmonitoring',
            name='confirm',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workmonitoring',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='care',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='building',
        ),
        migrations.AddField(
            model_name='medicine',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hatchery.building'),
        ),
        migrations.AlterField(
            model_name='tanktype',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='work',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Feed'), (1, 'Heal'), (2, 'Clean'), (3, 'Monitor'), (4, 'Maintenance'), (5, 'About')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workmonitoring',
            name='path',
            field=models.FileField(null=True, upload_to='uploads/path/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='workmonitoring',
            name='tank_planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tankPlannings', to='hatchery.tankplanning'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('building', 'code')},
        ),
        migrations.CreateModel(
            name='ResultPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('result_breed_numbers', models.FloatField()),
                ('shrimp_size', models.FloatField()),
                ('price', models.FloatField()),
                ('revenue', models.FloatField()),
                ('survival_rate', models.FloatField()),
                ('food_total', models.FloatField()),
                ('revenue_total', models.FloatField()),
                ('cost', models.FloatField()),
                ('profit', models.FloatField()),
                ('percent_profit', models.FloatField()),
                ('tank_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatchery.tankplanning')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='uploads/file/%Y/%m')),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_report', to=settings.AUTH_USER_MODEL)),
                ('tank_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tankPlanning_report', to='hatchery.tankplanning')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='season',
            name='status',
        ),
        migrations.DeleteModel(
            name='BuildingType',
        ),
    ]
