# Generated by Django 4.0.7 on 2022-08-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('name', 'code')},
        ),
    ]
