# Generated by Django 4.0.7 on 2022-08-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0002_alter_season_unique_together_season_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimptype',
            name='color',
        ),
        migrations.AddField(
            model_name='shrimptype',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='group_id',
            field=models.IntegerField(),
        ),
    ]
