# Generated by Django 4.0.7 on 2024-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0004_buildingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankplanning',
            name='days_rearing',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tankplanning',
            name='density',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tankplanning',
            name='rearing_phase',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tankplanning',
            name='shrimp_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
